In [59]:
import pandas as pd

In [60]:
car_sales_original_df = pd.read_csv("car_data.csv")

In [61]:
car_sales_original_df.head(5)

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
0,C_CND_000001,1/2/2022,Geraldine,Male,13500,Buddy Storbeck's Diesel Service Inc,Ford,Expedition,DoubleÂ Overhead Camshaft,Auto,Black,26000,06457-3834,SUV,8264678,Middletown
1,C_CND_000002,1/2/2022,Gia,Male,1480000,C & M Motors Inc,Dodge,Durango,DoubleÂ Overhead Camshaft,Auto,Black,19000,60504-7114,SUV,6848189,Aurora
2,C_CND_000003,1/2/2022,Gianna,Male,1035000,Capitol KIA,Cadillac,Eldorado,Overhead Camshaft,Manual,Red,31500,38701-8047,Passenger,7298798,Greenville
3,C_CND_000004,1/2/2022,Giselle,Male,13500,Chrysler of Tri-Cities,Toyota,Celica,Overhead Camshaft,Manual,Pale White,14000,99301-3882,SUV,6257557,Pasco
4,C_CND_000005,1/2/2022,Grace,Male,1465000,Chrysler Plymouth,Acura,TL,DoubleÂ Overhead Camshaft,Auto,Red,24500,53546-9427,Hatchback,7081483,Janesville

In [62]:
car_sales_original_df.tail(5)

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
23901,C_CND_023902,12/31/2023,Martin,Male,13500,C & M Motors Inc,Plymouth,Voyager,Overhead Camshaft,Manual,Red,12000,60504-7114,Passenger,8583598,Pasco
23902,C_CND_023903,12/31/2023,Jimmy,Female,900000,Ryder Truck Rental and Leasing,Chevrolet,Prizm,DoubleÂ Overhead Camshaft,Auto,Black,16000,06457-3834,Hardtop,7914229,Middletown
23903,C_CND_023904,12/31/2023,Emma,Male,705000,Chrysler of Tri-Cities,BMW,328i,Overhead Camshaft,Manual,Red,21000,99301-3882,Sedan,7659127,Scottsdale
23904,C_CND_023905,12/31/2023,Victoire,Male,13500,Chrysler Plymouth,Chevrolet,Metro,DoubleÂ Overhead Camshaft,Auto,Black,31000,53546-9427,Passenger,6030764,Austin
23905,C_CND_023906,12/31/2023,Donovan,Male,1225000,Pars Auto Sales,Lexus,ES300,DoubleÂ Overhead Camshaft,Auto,Pale White,27500,38701-8047,Hardtop,7020564,Middletown

In [63]:
car_sales_original_df.shape

(23906, 16)

In [64]:
car_sales_original_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23906 entries, 0 to 23905
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_id         23906 non-null  str
 1   Date           23906 non-null  str
 2   Customer Name  23905 non-null  str
 3   Gender         23906 non-null  str
 4   Annual Income  23906 non-null  int64
 5   Dealer_Name    23906 non-null  str
 6   Company        23906 non-null  str
 7   Model          23906 non-null  str
 8   Engine         23906 non-null  str
 9   Transmission   23906 non-null  str
 10  Color          23906 non-null  str
 11  Price ($)      23906 non-null  int64
 12  Dealer_No      23906 non-null  str
 13  Body Style     23906 non-null  str
 14  Phone          23906 non-null  int64
 15  Dealer_Region  23906 non-null  str
dtypes: int64(3), str(13)
memory usage: 2.9 MB

In [65]:
car_sales_original_df.nunique()

Car_id           23906
Date               612
Customer Name     3021
Gender               2
Annual Income     2508
Dealer_Name         28
Company             30
Model              154
Engine               2
Transmission         2
Color                3
Price ($)          870
Dealer_No            7
Body Style           5
Phone            23804
Dealer_Region        7
dtype: int64

In [66]:
car_sales_original_df.describe(include='all')

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
count,23906,23906,23905,23906,2.390600e+04,23906,23906,23906,23906,23906,23906,23906.000000,23906,23906,2.390600e+04,23906
unique,23906,612,3021,2,NaN,28,30,154,2,2,3,NaN,7,5,NaN,7
top,C_CND_000001,9/5/2023,Thomas,Male,NaN,Progressive Shippers Cooperative Association No,Chevrolet,Diamante,DoubleÂ Overhead Camshaft,Auto,Pale White,NaN,85257-3102,SUV,NaN,Austin
freq,1,190,92,18798,NaN,1318,1819,418,12571,12571,11256,NaN,3814,6374,NaN,4135
mean,NaN,NaN,NaN,NaN,8.308403e+05,NaN,NaN,NaN,NaN,NaN,NaN,28090.247846,NaN,NaN,7.497741e+06,NaN
std,NaN,NaN,NaN,NaN,7.200064e+05,NaN,NaN,NaN,NaN,NaN,NaN,14788.687608,NaN,NaN,8.674920e+05,NaN
min,NaN,NaN,NaN,NaN,1.008000e+04,NaN,NaN,NaN,NaN,NaN,NaN,1200.000000,NaN,NaN,6.000101e+06,NaN
25%,NaN,NaN,NaN,NaN,3.860000e+05,NaN,NaN,NaN,NaN,NaN,NaN,18001.000000,NaN,NaN,6.746495e+06,NaN
50%,NaN,NaN,NaN,NaN,7.350000e+05,NaN,NaN,NaN,NaN,NaN,NaN,23000.000000,NaN,NaN,7.496198e+06,NaN
75%,NaN,NaN,NaN,NaN,1.175750e+06,NaN,NaN,NaN,NaN,NaN,NaN,34000.000000,NaN,NaN,8.248146e+06,NaN
max,NaN,NaN,NaN,NaN,1.120000e+07,NaN,NaN,NaN,NaN,NaN,NaN,85800.000000,NaN,NaN,8.999579e+06,NaN

In [67]:
car_sales_df = car_sales_original_df.drop(['Car_id', 'Customer Name', 'Dealer_Name', 'Engine', 'Transmission','Dealer_No ', 'Phone'], axis=1)

In [68]:
car_sales_df['Date'] = pd.to_datetime(car_sales_df['Date'], errors='coerce')
car_sales_df.rename(columns={'Price ($)': 'Price', 'Annual Income': 'Annual_Income', 'Body Style': 'Body_Style'}, inplace=True)

In [69]:
car_sales_df.shape

(23906, 9)

In [70]:
car_sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 23906 entries, 0 to 23905
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           23906 non-null  datetime64[us]
 1   Gender         23906 non-null  str
 2   Annual_Income  23906 non-null  int64
 3   Company        23906 non-null  str
 4   Model          23906 non-null  str
 5   Color          23906 non-null  str
 6   Price          23906 non-null  int64
 7   Body_Style     23906 non-null  str
 8   Dealer_Region  23906 non-null  str
dtypes: datetime64[us](1), int64(2), str(6)
memory usage: 1.6 MB

In [71]:
car_sales_df.head(5)

,Date,Gender,Annual_Income,Company,Model,Color,Price,Body_Style,Dealer_Region
0,2022-01-02,Male,13500,Ford,Expedition,Black,26000,SUV,Middletown
1,2022-01-02,Male,1480000,Dodge,Durango,Black,19000,SUV,Aurora
2,2022-01-02,Male,1035000,Cadillac,Eldorado,Red,31500,Passenger,Greenville
3,2022-01-02,Male,13500,Toyota,Celica,Pale White,14000,SUV,Pasco
4,2022-01-02,Male,1465000,Acura,TL,Red,24500,Hatchback,Janesville

In [72]:
for col in car_sales_original_df.select_dtypes(include='str').columns:
    has_trailing_space = car_sales_original_df[col].astype(str).str.endswith(' ').any()
    print(col, has_trailing_space)

Car_id False
Date False
Customer Name False
Gender False
Dealer_Name False
Company False
Model False
Engine False
Transmission False
Color False
Dealer_No  False
Body Style False
Dealer_Region False